### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by yvesbou** [yvesbou/ICO_LW3#1]
## todos

- [ ] customise themes (dark and light theme)
- [ ] center the card
- [ ] add input field
- [ ] buy button
